export const AUTHENTICATION = 'AUTHENTICATION';
export const EXCHANGE = 'EXCHANGE';
export const PASSWORD_RESET = 'PASSWORD_RESET';
export const INVITATION = 'INVITATION';
export const TOTP_ENROLL = 'TOTP_ENROLL';
export const EMAIL_VERIFICATION = 'EMAIL_VERIFICATION';
